services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: polariswu/db:latest
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: frontend-app/Dockerfile
    image: polariswu/frontend-app:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
