name: DB Client CI/CD

on:
  pull_request:
    branches: [main]                # Run on any PR targeting main
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
  workflow_dispatch:                # Allows manual trigger with a version input
    inputs:
      version:
        description: 'Image version'  # Tag for Docker image
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                   # Fetch the code

      - name: Set up Python
        uses: actions/setup-python@v4               # Install Python toolchain
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pymongo python-dotenv pytest pytest-cov
                                                     # Bring in test & DB libs

      - name: Run DB client unit tests
        run: |
          cd db
          pytest test_mongo_client.py --cov=. --cov-report=term-missing
                                                     # Execute your test suite

  push_to_docker_hub:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                   # Ensure code is present

      - name: Log in to Docker Hub
        uses: docker/login-action@v2                # Authenticate for push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push DB Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/db:${{ github.event.inputs.version }} ./db
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/db:${{ github.event.inputs.version }}
                                                     # Tag & upload to Docker Hub