name: DB CI

on:
  pull_request:
    branches: [main]                   # Run build+test on PRs against main
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
  push:
    branches: [main]                   # Run full pipeline on pushes to main
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'   # Manual input for tagging
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies & run tests
        run: |
          pip install pymongo python-dotenv pytest pytest-cov
          cd db
          pytest test_mongo_client.py --cov=. --cov-report=term-missing

  push_to_docker_hub:
    if: github.event_name != 'pull_request'    # Skip on PRs
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine image tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2           # Authenticate with Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push DB image
        run: |
          # point at db/Dockerfile but use the entire repo as context
          docker build -f db/Dockerfile \
                        -t ${{ secrets.DOCKERHUB_USERNAME }}/db:$TAG \
                        .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/db:$TAG
