name: DB Client CI/CD

on:
  push:
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
  pull_request:
    paths:
      - 'db/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pymongo
          pip install unittest-xml-reporting  # optional for nice output
          pip install python-dotenv
          pip install pytest pytest-cov

      - name: Run database client unit tests
        run: |
          cd db
          pytest test_mongo_client.py --cov=. --cov-report=term-missing

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./db/Dockerfile
          push: true
          tags: polariswu/db:latest
