name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'frontend-app/**'
      - 'app.py'
      - 'requirements.txt'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend-app/**'
      - 'app.py'
      - 'requirements.txt'


jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports: ["27017:27017"]
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://localhost:27017/project5_db   # or my_frontend_tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Wait for MongoDB
        run: |
          until mongo --host localhost --eval "print('ok')"; do sleep 2; done
          
      - name: Run frontend tests
        run: |
          cd frontend-app
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-app
          file: ./frontend-app/Dockerfile
          push: true
          tags: polariswu/frontend-app:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Trigger DO App Platform deployment
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}